Update README.md
Otus-DevOps-2022-11/k0ctrh_infra pull request #2
Opened 2022-12-17 13:38 UTC by k0ctrh

add selfhomework3 answers

2022-12-18 12:29 UTC, mrgreyves reviewed
Здравствуйте!
Для чего этот пуллреквест?

2022-12-18 16:30 UTC, k0ctrh commented
Промежуточный этап домашней работы.

2022-12-19 07:38 UTC, k0ctrh commented
ДЗ на прверку

2022-12-19 18:55 UTC, mrgreyves requested changes
Здравствуйте!)
Когда добавляете пр в качестве промежуточного этапа работы стоит указывать в название либо WIP, либо DRAFT, тогда сразу будет понятно что еще идет активная работа =)
У вас не хватает файлов из первого дз, а именно github workflow тестов
Стоит их добавить
ДЗ возвращаю на доработку

2022-12-20 07:44 UTC, k0ctrh commented
Добрый день!
Наличие файлов поправил, тесты прошли. Прошу проверить.

2022-12-20 14:20 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь все хорошо
ДЗ принимаю =)

2022-12-20 14:21 UTC, k0ctrh commented
> Здравствуйте!) Вот теперь все хорошо ДЗ принимаю =)

Благодарю!

2022-12-20 16:17 UTC, merged