Ansible 2
Otus-DevOps-2022-11/k0ctrh_infra pull request #8
Opened 2023-01-31 18:15 UTC by k0ctrh

# Выполнено ДЗ №

 - [x] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2023-01-31 18:17 UTC, k0ctrh commented
Никак не могу понять причину ошибкти и устранить ее.

2023-02-02 17:08 UTC, mrgreyves requested changes
Здравствуйте!)
Ошибка видимо протянулась из дз в пакером
Нужно добавить файл с фейковым ключом
Ну и про переменную я вам написал
Выглядит как приключение на 10 минут =)

2023-02-02 17:08 UTC, mrgreyves commented on packer/variables.json.example
> +            "folder_id1": "12sdfsdfsdfsdf3",
folder_id1 - не корректная переменная =)

2023-02-02 17:47 UTC, k0ctrh commented on packer/variables.json.example
> +            "folder_id1": "12sdfsdfsdfsdf3",
Имя поменялось в попытках обойти ошибку..

2023-02-02 18:23 UTC, k0ctrh commented
Файл я добавил, переменную исправил, но ошибка не изменилась. Файл в папке, но пишет что его нет либо не прочитать.

2023-02-02 18:32 UTC, k0ctrh commented
Нашел ошибку, до него был неверно прописан путь.

2023-02-05 10:57 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь точно апрув ^_^

2023-02-06 08:40 UTC, merged