Ansible 3
Otus-DevOps-2022-11/k0ctrh_infra pull request #9
Opened 2023-02-06 11:44 UTC by k0ctrh

# Выполнено ДЗ №

 - [х] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2023-02-06 11:45 UTC, k0ctrh commented
Добрый день!
Прошу проверить, не могу разобраться почему не проходит тест.

2023-02-08 12:18 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Оставил комментарий по ошибке, попробуйте исправить
Выглядит как приключение на 15 минут =)

2023-02-08 12:18 UTC, mrgreyves commented on ansible/playbooks/app.yml
> +    - jdauphant.nginx
Интегрирована внешняя роль
Тест пытается ее проверить
Ее конечно же нет в репозитории, от этого и ошибка

2023-02-08 13:02 UTC, k0ctrh commented on ansible/playbooks/app.yml
> +    - jdauphant.nginx
Но мы же ее в gitignore вносим и ее в репозитории и быть не должно. Разве не так?

2023-02-08 14:01 UTC, k0ctrh commented
Я закомментировал роль в плейбуке и тест прошел, но я не уверен, что это правильное решение.

2023-02-11 15:47 UTC, mrgreyves approved these changes
Здравствуйте!)
Это нормальное решение, так как эта роль внешняя для нас
ДЗ принимаю =)

2023-02-12 07:42 UTC, merged